ALTER TABLE INFORMACJE_O_DOSTAWIE
ADD CONSTRAINT ID_dostawy 
FOREIGN KEY (ID_dostawy) REFERENCES DOSTAWY(ID_dostawy);

ALTER TABLE INFORMACJE_O_DOSTAWIE
ADD CONSTRAINT ID_magazynu 
FOREIGN KEY (ID_magazynu) REFERENCES MAGAZYNY(ID_magazynu);

ALTER TABLE KOSZTY_UTRZYMANIA
ADD CONSTRAINT ID_miesiaca_zarobkow 
FOREIGN KEY (ID_miesiaca_zarobkow) REFERENCES ZAROBKI(ID_miesiaca_zarobkow);

ALTER TABLE ZAROBKI
ADD CONSTRAINT ID_banku 
FOREIGN KEY (ID_banku) REFERENCES FINANSE(ID_banku);
