ALTER TABLE LOKAL
ADD CONSTRAINT ID_ogrzewania FOREIGN KEY (ID_ogrzewania) 
REFERENCES OGRZEWANIE(ID_ogrzewania);

ALTER TABLE LOKAL
ADD CONSTRAINT ID_adresu FOREIGN KEY (ID_adresu) 
REFERENCES ADRES(ID_adresu);

ALTER TABLE KASY
ADD CONSTRAINT ID_pracownika FOREIGN KEY (ID_pracownika) 
REFERENCES PRACOWNICY(ID_pracownika);
