ALTER TABLE DOSTAWCY
ADD CONSTRAINT ID_dostawczaka
FOREIGN KEY (ID_adresu) REFERENCES DOSTAWCZAKI(ID_dostawczaka);

ALTER TABLE DOSTAWCY
ADD CONSTRAINT ID_dostawy
FOREIGN KEY (ID_dostawy) REFERENCES DOSTAWY(ID_dostawy);

ALTER TABLE DOSTAWY
ADD CONSTRAINT ID_dzialu
FOREIGN KEY (ID_dzialu) REFERENCES DZIAL(ID_dzialu);

ALTER TABLE DOSTAWY
ADD CONSTRAINT ID_zamowienia
FOREIGN KEY (ID_zamowienia) REFERENCES ZAMOWIENIE(ID_zamowienia);

ALTER TABLE SPRZEDAZ
ADD CONSTRAINT ID_wydatkow
FOREIGN KEY (ID_wydatkow) REFERENCES KOSZTY_UTRZYMANIA(ID_wydatkow);
