ALTER TABLE FAKTURA_SPRZEDAZY
ADD CONSTRAINT ID_klienta
FOREIGN KEY (ID_klienta)
REFERENCES KLIENT(ID_klienta);

ALTER TABLE FAKTURA_SPRZEDAZY
ADD CONSTRAINT nr_tel1
FOREIGN KEY (nr_tel1)
REFERENCES KONTAKTY(nr_tel1);

ALTER TABLE FAKTURA_SPRZEDAZY
ADD CONSTRAINT ID_produktu
FOREIGN KEY (ID_produktu)
REFERENCES PRODUKTY(ID_produktu);

ALTER TABLE ZAMOWIENIE
ADD CONSTRAINT ID_produktu
FOREIGN KEY (ID_produktu)
REFERENCES PRODUKTY(ID_produktu);
