ALTER TABLE DZIALKA
ADD CONSTRAINT ID_adresu
FOREIGN KEY (ID_adresu) REFERENCES ADRES(ID_adresu);

ALTER TABLE DZIALKA
ADD CONSTRAINT ID_lokalu
FOREIGN KEY (ID_lokalu) REFERENCES LOKAL(ID_lokalu);

ALTER TABLE LOKALIZACJA
ADD CONSTRAINT ID_adresu
FOREIGN KEY (ID_adresu) REFERENCES ADRES(ID_adresu);

ALTER TABLE PARKING
ADD CONSTRAINT ID_lokalu
FOREIGN KEY (ID_lokalu) REFERENCES LOKAL(ID_lokalu);

ALTER TABLE PARKING
ADD CONSTRAINT ID_adresu
FOREIGN KEY (ID_adresu) REFERENCES ADRES(ID_adresu);

ALTER TABLE DOSTAWCZAKI
ADD CONSTRAINT ID_dostawcy
FOREIGN KEY (ID_dostawcy) REFERENCES DOSTAWCY(ID_dostawcy);
